name: Creatore FoundryOS 88
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compila il mio OS
      run: |
        sudo apt-get update && sudo apt-get install -y debootstrap squashfs-tools xorriso
        mkdir -p chroot && sudo debootstrap --arch=amd64 stable chroot http://deb.debian.org/debian/
        sudo cp *.sh chroot/
        # Esegue i tuoi script in automatico
        for f in chroot/*.sh; do sudo chmod +x $f && sudo chroot chroot /bin/bash /$(basename $f); done
        sudo xorriso -as mkisofs -r -V "FoundryOS88" -o FoundryOS88.iso chroot/
    - name: Salva il file pronto
      uses: actions/upload-artifact@v4
      with:
        name: FoundryOS88-Immagine-Pronta
        path: FoundryOS88.iso
